# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 文武科技社
subtitle: 一个有科技感的个人博客
description:  一个有科技感的个人博客
keywords: 文武科技社,科技,黑苹果,python,java,程序小黑,小黑
author: 程序小黑
language: zh-CN
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://chengxuxiaohei.cn/
root: /
permalink: :title.html
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: README.md

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 8
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next-load

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  - type: git
    repository: git@github.com:dongyubin/dongyubin.github.io.git
    branch: master
  - type: baidu_url_submitter
  
# git@gitee.com:wangdudyb/blog.git
search:
  path: search.xml
  field: post
  format: html
  limit: 10000
  
# hexo-neat
# 博文压缩
neat_enable: true
# 压缩html
neat_html:
  enable: true
  exclude:
# 压缩css  
neat_css:
  enable: true
  exclude:
    - '**/*.min.css'
# 压缩js
neat_js:
  enable: true
  mangle: true
  output:
  compress:
  exclude:

sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml
  
article_emoji:
  full: true
  style:
    display: inline
    padding: 10px

tabs:
  enable: true
  transition:
    tabs: true
    labels: true
  border_radius: 3
  
aplayer:
  meting: true
  
encrypt:
  enable: true
  
markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: true
    linkify: true
    typographer: true
    quotes: '“”‘’'
  plugins:
    - markdown-it-footnote
    - markdown-it-sup
    - markdown-it-sub
    - markdown-it-abbr
    - markdown-it-emoji
  anchors:
    level: 2
    collisionSuffix: 'v'
    permalink: true
    permalinkClass: header-anchor
    permalinkSymbol: ¶

  
baidu_url_submit:
  count: 200 ## 提交最新的一个链接
  host: chengxuxiaohei.cn ## 在百度站长平台中注册的域名
  token: Brjn3doMme2UvFir ## 请注意这是您的秘钥， 所以请不要把博客源代码发布在公众仓库里!
  path: baidu_urls.txt ## 文本文档的地址， 新链接会保存在此文本文档里